### PR TITLE
Added .travis.yml

### PR DESCRIPTION
**Pull request by jpic**
This should let you know easily if a PR breaks anything !

See it in action: https://travis-ci.org/jpic/jenkins-formula

It's interresting to see that jenkins.nginx includes nginx but not jenkins. If it did, it would look a bit cleaner (ie. we could replace `jenkins,jenkins.nginx` by just `jenkins.nginx` in this PR).

### CODE REVIEW

**Comment by whiteinge** [comment]
:+1:

**Comment by whiteinge** [comment]
Separate sls files each with a single purpose increases their reusability. Gluing them together in a top file or as you've done here with state.sls is a great way to go.

Thanks for the testing addition!

**Comment by jpic** [comment]
That makes sense however shouldn't it be the same for nginx ?

Le 18 mai 2015 18:06, "Seth House" <notifications@github.com> a écrit :
>
> Separate sls files each with a single purpose increases their
reusability. Gluing them together in a top file or as you've done here with
state.sls is a great way to go.

**Comment by jpic** [comment]
BTW I should probably have mentioned that you need to enable the repo in travis for this to have any effect.

**Comment by whiteinge** [comment]
Yes. Not all formulas conform to this pattern (yet).

**Comment by whiteinge** [comment]
Ah, right. Thanks. Enabled.

**Comment by jpic** [comment]
> Yes. Not all formulas conform to this pattern (yet).

So, if I understand correctly, it would be good to create an issue regarding the removal of nginx inclusion from jenkins.nginx ?

**Comment by puneetk** [comment]
The inclusion can be removed, if we can explain how its dependent on an nginx state in the documents.

**Comment by gravyboat** [comment]
@jpic @whiteinge @puneetk So the current standard in most formulas is that we DON'T have a dependency like the nginx formula on the jenkins formula. We've been doing this for a while mostly so new users weren't downloading 30 different formulas to make a single formula worked. This is especially apparent over in the PHP formula.

**Pull request merged**
