### PR TITLE
Fix #21: nginx server_name configuration

### LINKED ISSUE #21: Allow setting server name
Currently, the [server_name](https://github.com/saltstack-formulas/jenkins-formula/blob/master/jenkins/files/nginx.conf#L10) nginx configuration variable for jenkins is commented.

It would be great if we could override it, so that other sites can live along with jenkins on this nginx configuration.

### PR DESCRIPTION
**Pull request by jpic**

### CODE REVIEW

**Comment by jpic** [comment]
Oops, it seems like the build failed because bootstrap failed:

```
The following packages have unmet dependencies:

 python-requests : Depends: python-urllib3 (>= 1.7.1) but it is not installable

E: Unable to correct problems, you have held broken packages.

 * ERROR: Failed to run install_ubuntu_stable_deps()!!!

 * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe

 * DEBUG: Killing logging pipe tee's with pid(s): 2286
```

**Comment by gravyboat** [comment]
It's similar enough to https://github.com/saltstack-formulas/jenkins-formula/pull/13 that I'm willing to merge it. Not sure about the server_name existing in map.jinja, but we can always modify that later. If anyone has opinions please feel free to voice them. Thanks @jpic!

**Comment by jpic** [comment]
Thanks @gravyboat, I thought we would have waited to fix the bootstrap script first to get the tests to pass before we merge but it's cool that I can get rid of my override for the nginx template !

**Comment by gravyboat** [comment]
@jpic Nah it's almost identical to that last one but with some extra details, and the old one was fine.

**Pull request merged**
