### PR TITLE
Changed pkg.lastest to pkg.installed. Moved server_name out of the ma…

### PR DESCRIPTION
**Pull request by GregMSThompson**
…p file.

A couple of small changes that I hope you think are ok. The first is a change to prevent the package from being auto updated, which can be dangerous especially with something like Jenkins were the odd bug has been known to be introduced into newer versions. I also, moved the package names into the map file to bring it in line with many of the other community formulas. The second if just to move the server_name out of the map file as it doesn't have a default value.

### CODE REVIEW

**Comment by puneetk** [comment]
can you please restore server_map with localhost as default. 
it's from a pull request with a valid use case

**Comment by GregMSThompson** [comment]
Sure, do you still want there to be a check to see if server_map is defined in the nginx.conf template?

**Comment by puneetk** [comment]
Actually a None is fine, we just need the key in the map so that the merge with the pillar.

**Comment by GregMSThompson** [comment]
Sure I can put it back to None. Just out of curiosity though, what is the use case that requires you to have a default of None in the map file and not just have it as a value to be defined in pillar outside of the default values in your map file?

**Comment by GregMSThompson** [comment]
Hi puneetk, apologies that it has taken me a while but I have now changed the code back to having server_name included in the map file. I hope it is now acceptable. Please let me know if it requires further changes. 

Many thanks,
Greg

**Pull request merged**
