### PR TITLE
need java

### PR DESCRIPTION
**Pull request by jmdcal**
you are going to need java to run jenkins...

### CODE REVIEW

**Comment by puneetk** [comment]
@jmdcal, nice nick, can you please look into fixing the errors from travisci

**Comment by iggy** [comment]
See #26

**Comment by jmdcal** [comment]
I am not going to have time right now to fix this Up, assuming that the package name is different on different os versions?

**Comment by babilen** [comment]
Exactly, one shouldn't assume that the package name is identical on all platforms. Which package to use where should be maintained in https://github.com/saltstack-formulas/jenkins-formula/blob/master/jenkins/map.jinja which is filtered by `os_family`.

**Comment by jpic** [comment]
What distribution is that for ?

On debian jessie java is a dependency of jenkins and there is no need to manually specify a java package to install.

**Comment by jmdcal** [comment]
This is for centos7

**Comment by jmdcal** [comment]
rpm -qpR jenkins-1.623-1.1.noarch.rpm 
```
/bin/sh
/bin/sh
/bin/sh
/bin/sh
/bin/sh
/usr/sbin/groupadd
/usr/sbin/useradd
config(jenkins) = 1.623-1.1
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
```

No java, it says here that you might need to install java. 
https://wiki.jenkins-ci.org/display/JENKINS/Installing+Jenkins+on+Red+Hat+distributions

**Comment by puneetk** [comment]
Heres what you could do  in the map.jinja 


```Saltstack
{% set jenkins = salt['grains.filter_by']({
    'default': {
        'user': 'jenkins',
        'group': 'jenkins',
        'home': '/var/lib/jenkins',
        'port': '80',
        'server_name': None,
       'pkgs': ['jenkins']
    },
   '# change it to the correct return from grains.get('os_family')
    'centos': {
        'user': 'jenkins',
        'group': 'jenkins',
        'home': '/var/lib/jenkins',
        'port': '80',
        'server_name': None,
       'pkgs': ['jenkins', java-1.7.0-openjdk, java-1.7.0-openjdk-devel.x86_64 ]
    },   
}, merge=salt['pillar.get']('jenkins:lookup')) %}
```
and then in the init.sls 

```
jenkins-pkgs:
  {% if grains['os_family'] in ['RedHat', 'Debian'] %}
  pkgrepo.managed:
    - humanname: Jenkins upstream package repository
    {% if grains['os_family'] == 'RedHat' %}
    - baseurl: http://pkg.jenkins-ci.org/redhat
    - gpgkey: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
    {% elif grains['os_family'] == 'Debian' %}
    - name: deb http://pkg.jenkins-ci.org/debian binary/
    - key_url: http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
    {% endif %}
    - require_in:
      - pkg: jenkins
  {% endif %}
  pkg.latest:
    - names: {{ jenkins.pkgs }}
    - refresh: True
  service.running:
    - enable: True
    - watch:
      - pkg: jenkins
```

That way its backwards compatible and allows you to use the formula for your os_family

**Comment by jmdcal** [comment]
I am closing this and converting it to an issue. https://github.com/saltstack-formulas/jenkins-formula/issues/29

**Comment by myoung34** [comment]
This doesnt need to be in the jenkins formula, you can [use the java formula](https://github.com/saltstack-formulas/java-formula) or [the sun java formula](https://github.com/saltstack-formulas/sun-java-formula) before applying any jenkins states

**Pull request closed without merging**
